# backend/services/local_import/repository/__init__.py
# ==============================
# 盘后数据导入 import - repository 包统一出口
# ==============================

from __future__ import annotations

from .batches import (
    generate_batch_id,
    create_batch,
    get_batch,
    list_all_batches_ordered,
    get_batches_by_state,
    get_current_running_batch,
    get_latest_queued_batch,
    get_oldest_queued_batch,
    get_last_effective_terminal_batch,
    get_latest_active_batch_by_signature,
    get_display_batch_meta,
    list_queued_batch_summaries,
    build_display_batch_view,
    build_status_snapshot,
    mark_batch_running,
    mark_batch_paused,
    mark_batch_queued_for_retry,
    mark_batch_terminal_state,
    update_batch_ui_message,
    delete_batch,
    delete_batches,
)
from .tasks import (
    create_tasks_for_batch,
    delete_tasks_for_batch,
    delete_tasks_for_batches,
    delete_tasks_except_batch_ids,
    delete_orphan_tasks,
    list_tasks_for_batch,
    get_next_queued_task,
    get_running_task,
    mark_task_running,
    get_task,
    mark_task_terminal,
    cancel_queued_tasks_in_batch,
    reset_retryable_tasks,
    mark_interrupted_running_tasks_failed,
    get_batch_counts,
)

__all__ = [
    "generate_batch_id",
    "create_batch",
    "get_batch",
    "list_all_batches_ordered",
    "get_batches_by_state",
    "get_current_running_batch",
    "get_latest_queued_batch",
    "get_oldest_queued_batch",
    "get_last_effective_terminal_batch",
    "get_latest_active_batch_by_signature",
    "get_display_batch_meta",
    "list_queued_batch_summaries",
    "build_display_batch_view",
    "build_status_snapshot",
    "mark_batch_running",
    "mark_batch_paused",
    "mark_batch_queued_for_retry",
    "mark_batch_terminal_state",
    "update_batch_ui_message",
    "delete_batch",
    "delete_batches",

    "create_tasks_for_batch",
    "delete_tasks_for_batch",
    "delete_tasks_for_batches",
    "delete_tasks_except_batch_ids",
    "delete_orphan_tasks",
    "list_tasks_for_batch",
    "get_next_queued_task",
    "get_running_task",
    "mark_task_running",
    "get_task",
    "mark_task_terminal",
    "cancel_queued_tasks_in_batch",
    "reset_retryable_tasks",
    "mark_interrupted_running_tasks_failed",
    "get_batch_counts",
]
